[package]
distribution = "2201.1.2"
name = "testing"
org = "samedytesting"
version = "0.1.0"

[build-options]
observabilityIncluded = true
# cloud = "k8s"
#[[platform.java11.dependency]]
# groupId = "io.ballerina.stdlib"
# artifactId = "jwt-native"
# version = "2.4.0"
#path = "./libs/jwt-native-2.4.0.jar"